<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>How to Pass Value in ES6 - Learn ES6</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" media="screen" href="../style.css" />
    <link rel="shortcut icon" href="../../logo-black.png">
</head>
<body>
    <main>
        <h1>Understanding ES6</h1>
        <h2>Promises</h2>
        <div class="section">
            <h3>Pt.1 - Fundamentals of Promise</h3>
            <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises">See the Reference</a>
            <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise">See also</a>
            <p>
                Promise is an action for setting temporarily the results on behalf of values what do not know at the moment.<br>
                By using Promise to return value what will set in the future, It can return result of unsynchronized
                process as same as synchlonized process.<br>
                The Promise object returns the eventual completion (or failure) of an asynchronous(a-synchronous : ÈùûÂêåÊúü) operation, and its resulting
            value.<br>
                Promise object can define following syntax.
                <pre class="prettyprint">
                <code>
                new Promise((resolve, reject)=>{
                    //Processing of something
                });</code>
                </pre>
            </p>
            <p>Functions which is passed to promise has 2 function as parameters.
                <ul>
                    <li><strong>resolve</strong> - pass to next value when process has successfully finished.</li>
                    <li><strong>reject</strong>- pass to next value when process has failed.</li>
                </ul>
                <span class="caption">*resolve and reject are the basic example. normally we use these one.</span>
            </p>
            <p>When resolve or reject which inside of Promise has been invoked, then or catch handler will have been invoked depends on that results.
                <pre class="prettyprint">
                <code>
                const promise = new Promise((resolve, reject) => {
                    //Processing of something
                });
                Promise
                    .then((result) => {
                        //Process in case of successfully finished
                    })
                    .catch((result) => {
                        //Process in case of failed
                    })
                </code>
                </pre>
            </p>
            <p>Promise is an action for setting temporarily the results on behalf of values what do not know at the moment.<br>
            By using Promise to return value what will set in the future, It can return result of unsynchronized
            process as same as synchlonized process.</p>
            <p>To understand Promises, Understanding each state and condition is important.<br>
            Promise has following condition.</p>
            <ul>
                <li><strong>pending</strong> - Initial state with unclear result</li>
                <li><strong>fulfilled</strong> - Means processing has successfully finished</li>
                <li><strong>rejected</strong> - Means processing has failed</li>
            </ul>
            <p>The state of when defined Promise object itself is <code>Pending</code>.<br>
                State will determine when resolve or reject has been invoked. then state will become either <code>fullfiled</code> or <code>rejected</code>.</p>
            <p>Promise which state has determined will call then or catch depends on the results of state to next value.<br>
            this is the structure of the instruction.</p>
            <img src="https://codeprep-prod.s3-ap-northeast-1.amazonaws.com/books/shliumlE87CNvzTuxH1lJlJmbGv-Cjo-Jm1A-623eRQ/es6/a4dc3fb8d19e8e90d3f14ea8be71418c027b0601/assets/images/images.001.png"/>
            <h4>input</h4>
            <pre class="prettyprint">
            <code>
            const promise = new Promise((resolve, reject) =>{
                /* 
                    ‚ñ≥
                    resolve - pass result to next function in case of processing has successed
                    reject - pass result to next function in case of processing has unsuccessed
                    *normally resolve and reject is used as a name of function
                */
            //return result after 100ms
            setTimeout(() => {
                resolve("one")
                }, 100);
            });
            promise.then(data => {
                /*
                    When resolve or reject has been invoked,
                    then or catch handler will be invoke depends on the results.
            
                    then - if the result was success
                    catch - if the result was unsuccess
                */
                //receive the data which passed by value on resolve
                console.log(data);//one(in resolve)
            });
            </code>
            </pre>
            <h4>output</h4>
            <pre>
            <code>
            one</code>
            </pre>
        </div>
        <div class="section">
            <h3>Pt.2 - Chain for each process of Promise</h3>
            <p>The process of Promise can chain by using <code>then</code>.<br>
            when callback functions of <code>then</code> returns value, it will be wrapped by <strong>Promise.resolve</strong>. 
            So that we can get the value by using <code>then</code>.</p>
            <h4>Input</h4>
            <pre class="prettyprint">
            <code>
            const lunch = new Promise ((resolve, reject) => {
                setTimeout(()=>{
                    resolve("üçî")
                }, 100)
            });
            lunch
                .then(data => {
                console.log(data);
            
                // in case of paprameter in then() erase the value,
                // then() can be chain, thanks to it'll be automatically
                // wrapped by Promise.resolve.
                return `${data}üçü`;
            })
            .then(data => {
                console.log(data);
                return`${data}ü•§`;
            })
            .then(data => {
                console.log(`${data} that's it!`)
            })</code>
            </pre>
            <h4>Output</h4>
            <pre>
            <code>
            üçî
            üçîüçü
            üçîüçüü•§ that's it!</code>
            </pre>
        </div>
        
        <div class="section">
            <h3>Pt.3 - Promise.resolve</h3>
            <p>By using <code>Promise.resolve()</code>, You can create Promise which state has already fixed even if without creating
            Promise object.</p>
            <pre>
            <code>
            // same with this below
            const promise = new Promise((resolve, reject) => {
            resolve("You got a API response!!");
            });
            </code>
            </pre>
            <h4>input</h4>
            <pre class="prettyprint">
            <code>
            const promiseResolve = Promise.resolve("You got an API response!");
            
            promiseResolve
            .then(data => {
            console.log("success!", data)
            });
            </code></pre>
            <h4>output</h4>
            <pre>
            <code>
            success! You got an API response!</code>
            </pre>
        </div>
        <div class="section">
            <h3>Pt.4 - Promise.reject</h3>
            <p>By using <code>Promise.reject()</code>, You can create Promise which state has already fixed even if without creating Promise object.<br>(Failed case of Promise.resolve)</p>
            <pre>
            <code>
            // same with this below
            const promise = new Promise((resolve, reject) => {
            resolve("You got a API response!!");
            });
            </code>
            </pre>
            <h4>input</h4>
            <pre class="prettyprint">
            <code>
            const promiseReject = Promise.reject("java.lang.NullPointerException");//failed example
            promiseReject
                .then(data => {
                console.log("Sucess!", data);
                })
            .catch(error => {
                console.log("failed!", error);
                });
            </code></pre>
            <h4>output</h4>
            <pre>
            <code>
            failed! java.lang.NullPointerException</code>
            </pre>
        </div>
        <div class="section">
            <h3>Pt.5 - Difference between Promise.catch and onRejected Handler</h3>
            <p>You can set 2 functions for the callback functions of <code>then</code>.</p>
            <ul>
                <li>onFullFilled - Success Processing</li>
                <li>onRejected - Failed Processing</li>
            </ul>
            <p><code>catch</code>and<code>onRejected</code>handler is the function which activates if Promise has rejected.</p>
            <p><code>onRejected</code>handler is the process for Promise which placed right before the processing. Because it can't process out of case for <code>onFullFilled</code> process if it happens, processing of promise in out of case might be impossible.<br>
            <code>catch</code>is the processing for then. So it's suggested that adding <code>catch</code> handler in last part of processing for Promise, as global handler for out of case.</p>
            <pre>
            <code>
            promise
            .then()
            .then()
            .then()
            .catch(
            // write processing for common out of cases
            );</code>
            </pre>
            <span class="caption"></span>
            <h4>input</h4>
            <pre class="prettyprint">
            <code>
            const promiseReject = Promise.reject("java.lang.NullPointerException");//failed example
            promiseReject
                .then(data => {
                console.log("Sucess!", data);
                }, error => {
                console.log("failed!", error);
                return error;
                })
                .then(data => {
                console.log("successed at last!", data);
                })
                .catch(error => {
                console.log("failed at last!", error);
                });
            </code></pre>
            <h4>output</h4>
            <pre>
            <code>
            failed! java.lang.NullPointerException
            successed at last! java.lang.NullPointerException</code>
            </pre>
        </div>
        <div class="section">
            <h3>Pt.6 - Promise.all</h3>
            <p><code>Promise.all</code>is used for invoke <code>then</code> handler right after processing of Promise has been finished.</p>
            <h4>input</h4>
            <pre class="prettyprint">
            <code>
            const rabbit = new Promise((resolve, reject) => {
                setTimeout(() => resolve("time of rabbit : 100ms"), 100);
            });
            const turtle = new Promise((resolve, reject) => {
                setTimeout(() => resolve("time of turtle : 300ms"), 300);
            });
            
            Promise.all([rabbit, turtle]).then(result => {
                const[timeForRabbit, timeForTurtle] = result;
                console.log(timeForRabbit);
                console.log(timeForTurtle);
            });
            </code></pre>
            <h4>output</h4>
            <pre>
            <code>
            time of rabbit : 100ms
            time of turtle : 300ms</code>
            </pre>
        </div>
        <div class="section">
            <h3>Pt.7 - Promise.race</h3>
            <p>If you want to invoke then handler when multiple processing of Promise has finished earliest among, use <code>Promise.race</code>.</p>
            <h4>input</h4>
            <pre class="prettyprint">
            <code>
            const rabbit = new Promise((resolve, reject) => {
            setTimeout(() => resolve("time of rabbit : 100ms"), 100);
            });
            const turtle = new Promise((resolve, reject) => {
            setTimeout(() => resolve("time of turtle : 300ms"), 300);
            });

            Promise.race([rabbit, turtle]).then(result => {
            console.log(result);///time of rabbit : 100ms
            });
            </code></pre>
            <h4>output</h4>
            <pre>
            <code>
            time of rabbit : 100ms</code>
            </pre>
        </div>
    </main>
    <footer>
        <ul>
            <li><a href="../01-Introduction/index.html">Introduction</a></li>
            <li><a href="../02-Arrow-function/index.html">Arrow funciton</a></li>
            <li><a href="../03-Destructuring/index.html">Destructuring</a></li>
            <li><a href="../04-How-to-pass-value/index.html">How to Pass Value in ES6</a></li>
            <li><a href="../05-Template-Strings/index.html">Template Strings</a></li>
            <li><a href="../06-Expanded-Object-Properties/index.html">Expanded Object Properties</a></li>
            <li><a href="../07-Classes/index.html">Classes</a></li>
            <li>Promises</li>
            <li><a href="../09-New-APIs/index.html">New API</a></li>
        </ul>
        <p class="copyright">&copy;SZDP / Kaai Suzuki</p>
    </footer>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
    <script>
        'use strict';
        ///Pt.1
        const promise = new Promise((resolve, reject) =>{
            /*  ‚ñ≥
                resolve - pass result to next function in case of processing has successed
                reject - pass result to next function in case of processing has unsuccessed
                *normally resolve and reject is used as a name of function
            */
            //return result after 100ms
            setTimeout(() => {
                resolve("one")
            }, 100);
        });
        promise.then(data => {
            /*
                When resolve or reject has been invoked, 
                then or catch handler will be invoke depends on the results.
                
                then - if the result was success
                catch - if the result was unsuccess
            */
            //receive the data which passed by value on resolve
            console.log(data);//one(in resolve)
        });

        ////Pt.2
        const lunch = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve("üçî")
            }, 100)
        });
        lunch
            .then(data => {
                console.log(data);

                // in case of paprameter in then() erase the value,
                // then() can be chain, thanks to it'll be automatically
                // wrapped by Promise.resolve.
                return `${data}üçü`;
            })
            .then(data => {
                console.log(data);
                return `${data}ü•§`;
            })
            .then(data => {
                console.log(`${data} that's it!`)
            });

        ///Pt.3
            const promiseResolve = Promise.resolve("You got an API response!");

            promiseResolve
                .then(data => {
                    console.log("success!", data)
                });

            ///Pt.4, 5
            const promiseReject = Promise.reject("java.lang.NullPointerException");//failed example
            promiseReject
                .then(data => {
                    console.log("Sucess!", data);
                }, error => {
                    console.log("failed!", error);
                    return error;
                })
                .then(data => {
                    console.log("successed at last!", data);
                })
                .catch(error => {
                    console.log("failed at last!", error);
                });

            ////Pt6, 7
            const rabbit = new Promise((resolve, reject) => {
                setTimeout(() => resolve("time of rabbit : 100ms"), 100);
            });
            const turtle = new Promise((resolve, reject) => {
                setTimeout(() => resolve("time of turtle : 300ms"), 300);
            });

            Promise.all([rabbit, turtle]).then(result => {
                const[timeForRabbit, timeForTurtle] = result;
                console.log(timeForRabbit);
                console.log(timeForTurtle);
            });

            Promise.race([rabbit, turtle]).then(result => {
                console.log(result);///time of rabbit : 100ms
            });
    </script>
</body>
</html>