<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>How to Pass Value in ES6 - Learn ES6</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="../style.css" />
    <link rel="shortcut icon" href="../../logo-black.png">
</head>
<body>
    <main>
        <h1>Understanding ES6</h1>
        <h2>Promises</h2>
        <div class="section">
            <h3>Fundamentals of Promise</h3>
            <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises">See the Reference</a>
            <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise">See also</a>
            <p>
                The Promise object represents the eventual completion (or failure) of an asynchronous operation, and its resulting
            value.<br>
                Promise object can define following syntax.
                <pre class="prettyprint">
                    <code>
                    new Promise((resolve, reject)=>{
                        //Processing of something
                    });</code>
                </pre>
            </p>
            <p>Functions which is passed to promise has 2 function as parameters.
                <ul>
                    <li>resolve - pass to next value when process has successfully finished.</li>
                    <li>reject - pass to next value when process has failed.</li>
                </ul>
                <span class="caption">*resolve and reject are the basic example. normally we use these one.</span>
            </p>
            <p>When resolve or reject which inside of Promise has been invoked, then or catch handler will have been invoked depends on that results.
                <pre class="prettyprint">
                <code>
                const promise = new Promise((resolve, reject) => {
                    //Processing of something
                });
                Promise
                    .then((result) => {
                        //Process in case of successfully finished
                    })
                    .catch((result) => {
                        //Process in case of failed
                    })
                </code>
                </pre>
            </p>
            <p>Promise is an action for setting temporarily the results on behalf of values what do not know at the moment.<br>
            By using Promise to return value what will set in the future, It can return result of unsynchronized
            process as same as synchlonized process.</p>
            <p>To understand Promises, Understanding each state and condition is important.<br>
            Promise has following condition.</p>
            <ul>
                <li><strong>pending</strong> - Initial state with unclear result</li>
                <li><strong>fulfilled</strong> - Means processing has successfully finished</li>
                <li><strong>rejected</strong> - Means processing has failed</li>
            </ul>
            <p>The state of when defined Promise object itself is <code>Pending</code>.<br>
                State will determine when resolve or reject has been invoked. then state will become either <code>fullfiled</code> or <code>rejected</code>.</p>
            <p>Promise which state has determined will call then or catch depends on the results of state to next value.<br>
            this is the structure of the instruction.</p>
            <img src="https://codeprep-prod.s3-ap-northeast-1.amazonaws.com/books/shliumlE87CNvzTuxH1lJlJmbGv-Cjo-Jm1A-623eRQ/es6/a4dc3fb8d19e8e90d3f14ea8be71418c027b0601/assets/images/images.001.png"/>
            <h4>input</h4>
            <pre class="prettyprint">
                <code>
                const promise = new Promise((resolve, reject) =>{
                    /* 
                        △
                        resolve - pass result to next function in case of processing has successed
                        reject - pass result to next function in case of processing has unsuccessed
                        *normally resolve and reject is used as a name of function
                    */
                //return result after 100ms
                setTimeout(() => {
                    resolve("one")
                    }, 100);
                });
                promise.then(data => {
                    /*
                        When resolve or reject has been invoked,
                        then or catch handler will be invoke depends on the results.
                
                        then - if the result was success
                        catch - if the result was unsuccess
                    */
                    //receive the data which passed by value on resolve
                    console.log(data);//one(in resolve)
                });
                </code>
            </pre>
            <h4>output</h4>
            <pre>
                <code>
                one</code>
            </pre>
        </div>
    </main>
    <footer>
        <ul>
            <li><a href="../01-Introduction/index.html">Introduction</a></li>
            <li><a href="../02-Arrow-function/index.html">Arrow funciton</a></li>
            <li><a href="../03-Destructuring/index.html">Destructuring</a></li>
            <li><a href="../04-How-to-pass-value/index.html">How to Pass Value in ES6</a></li>
            <li><a href="../05-05-Template-Strings/index.html">Template Strings</a></li>
            <li><a href="../06-Expanded-Object-Properties/index.html">Expanded Object Properties</a></li>
            <li><a href="../07-Classes/index.html">Classes</a></li>
            <li>Promises</li>
            <li><a href="../09-New-APIs/index.html">New API</a></li>
        </ul>
        <p class="copyright">&copy;SZDP / Kaai Suzuki</p>
    </footer>
    <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
    <script>
        'use strict';
        ///Pt.1
        const promise = new Promise((resolve, reject) =>{
            /*  △
                resolve - pass result to next function in case of processing has successed
                reject - pass result to next function in case of processing has unsuccessed
                *normally resolve and reject is used as a name of function
            */
            //return result after 100ms
            setTimeout(() => {
                resolve("one")
            }, 100);
        });
        promise.then(data => {
            /*
                When resolve or reject has been invoked, 
                then or catch handler will be invoke depends on the results.
                
                then - if the result was success
                catch - if the result was unsuccess
            */
            //receive the data which passed by value on resolve
            console.log(data);//one(in resolve)
        });
    </script>
</body>
</html>